version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - "minio-data:/data"
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=j0SgwZVhmuVe
      - MINIO_BUCKET_NAME=my-bucket
    command: server /data  --address :8000 --console-address :8001
volumes:
  minio-data: