- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest # noqa package-latest
  when: common_upgrade_packages | bool

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Enable chronyd
  ansible.builtin.systemd_service:
    name: chronyd
    enabled: true
    state: started

- name: Enable firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: true
    state: started

- name: Allow GitLab services through firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ common_firewalld_services }}"
